---
abstract: "A Task to install all BINGOS' Module::Install extensions"
author:
  - 'Chris Williams <chris@bingosnet.co.uk>'
build_requires:
  ExtUtils::MakeMaker: 6.42
  Test::More: 0.47
configure_requires:
  ExtUtils::MakeMaker: 6.42
distribution_type: module
generated_by: 'Module::Install version 1.00'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Task-Module-Install-BINGOS
no_index:
  directory:
    - inc
    - t
requires:
  Module::Install: 1
  Module::Install::AssertOS: 0.1
  Module::Install::AutoLicense: 0.08
  Module::Install::AutomatedTester: 0.02
  Module::Install::CheckLib: 0.08
  Module::Install::GithubMeta: 0.1
  Module::Install::NoAutomatedTesting: 0.06
  Module::Install::ReadmeFromPod: 0.12
  perl: 5.6.0
resources:
  homepage: http://github.com/bingos/perl-task-modules/tree
  license: http://dev.perl.org/licenses/
  repository: git://github.com/bingos/perl-task-modules.git
version: 1.02
