---
abstract: 'A Task to install all BINGOS'' Module::Install extensions'
author:
  - 'Chris Williams <chris@bingosnet.co.uk>'
build_requires:
  ExtUtils::MakeMaker: 6.42
  Test::More: 0.47
configure_requires:
  ExtUtils::MakeMaker: 6.42
distribution_type: module
generated_by: 'Module::Install version 0.87'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Task-Module-Install-BINGOS
no_index:
  directory:
    - inc
    - t
requires:
  Module::Install: 0.87
  Module::Install::AssertOS: 0.1
  Module::Install::AutoLicense: 0.02
  Module::Install::AutomatedTester: 0.02
  Module::Install::CheckLib: 0.02
  Module::Install::GithubMeta: 0.02
  Module::Install::NoAutomatedTesting: 0.06
  Module::Install::ReadmeFromPod: 0.06
  perl: 5.6.0
resources:
  license: http://dev.perl.org/licenses/
version: 1.00
